framework:
    #### REDIS CACHE
    cache:
        pools:
            pimcore.cache.pool:
                public: true
                tags: true
                default_lifetime: 31536000 # 1 year
                adapter: pimcore.cache.adapter.redis_tag_aware
        default_redis_provider: "redis://##redis_hostname##:##redis_port##/##redis_database##"

doctrine:
    dbal:
        connections:
            default:
                driver: pdo_mysql
                host: ##mysql_hostname##
                port: ##mysql_port##
                dbname: ##mysql_database##
                user: ##mysql_user##
                password: ##mysql_password##
                charset: UTF8MB4
                mapping_types:
                    enum: string
                    bit: boolean
                server_version: 5.7